[workspace]
members = ["crates/coherence-core-db", "crates/coherence-core-db-tui", "crates/coherence-test-world"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
rust-version = "1.76"
authors = ["Nikolay Konovalov"]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
unwrap_used = "warn"
expect_used = "warn"

[workspace.dependencies]
toml = "0.8.19"
