CREATE TABLE IF NOT EXISTS specs (
  id VARCHAR(191) PRIMARY KEY,
  title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS acceptance_criteria (
  id VARCHAR(191) PRIMARY KEY,
  spec_id VARCHAR(191) NOT NULL,
  title TEXT NOT NULL
);
